replicaCount: 2

image:
  repository: gcu-profit-dev.kr-central-2.kcr.dev/arcadia-nextjs/arcadia-nextjs
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: kic-registry

service:
  type: ClusterIP
  port: 80

serviceAccount:
  enabled: false

ingress:
  enabled: true
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"  # cert-manager의 Issuer 이름을 적절하게 설정
  hosts:
    - host: arcadia.p-e.kr
      paths: /

  tls:
    - secretName: arcadia-tls
      hosts:
        - arcadia.p-e.kr

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

nodeSelector: {}

tolerations: []

affinity: {}
