replicaCount: 2

image:
  repository: gcu-profit-dev.kr-central-2.kcr.dev/arcadia-nextjs/arcadia-fe
  image: 17
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: kic-registry

service:
  type: ClusterIP
  port: 80

serviceAccount:
  enabled: false

ingress:
  enabled: true
  annotations:
    - cert-manager.io/issuer: "letsencrypt-prod"  # cert-manager의 Issuer 이름을 적절하게 설정
    - kubernetes.io/ingress.class: nginx
    - kubernetes.io/tls-acme: "true"
    - nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    - nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  hosts:
    - host: arcadia.p-e.kr
      paths:
        - path: /
          pathType: Prefix

  tls:
    - secretName: arcadia-tls
      hosts:
        - arcadia.p-e.kr

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70 

nodeSelector: {}

tolerations: []

affinity: {}