apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arcadia-fe.fullname" . }}
  labels: {{- include "arcadia-fe.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "arcadia-fe.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "arcadia-fe.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
              name: http
          resources: {{- toYaml .Values.resources | nindent 12 }}
