apiVersion: v1
kind: Service
metadata:
  name: {{ include "arcadia-fe.fullname" . }}
  labels: 
    {{- include "arcadia-fe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector: 
    {{- include "arcadia-fe.selectorLabels" . | nindent 4 }}
